//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using WebUI.Controllers
        ///@using WebUI
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;@RenderSection(&quot;PageName&quot;, true)&lt;/title&gt;
        ///    &lt;link href=&quot;@Url.Content(&quot;~/Content/css/main.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;link href=&quot;@Url.Content(&quot;~/Content/css/dropdown.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;link href=&quot;@Url.Content(&quot;~/Content/css/tooltip.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;link href=&quot;@Url.Content(&quot;~/Content/css/jquery-ui.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model WebUI.Areas.Bots.Models.AdvancedBotTypeViewModel
        ///@{
        ///    ViewBag.Title = &quot;Index&quot;;
        ///}
        ///@{
        ///    Layout = &quot;~/Areas/Bots/Views/Shared/_Main.cshtml&quot;;
        ///    
        ///}
        ///@using (Html.BeginForm(MVC.Bots.AdvancedBotType.Save()))
        ///{
        ///    @Html.ValidationSummary(false)
        ///    &lt;fieldset&gt;
        ///        &lt;legend&gt;AdvancedBotTypeViewModel&lt;/legend&gt;&lt;span&gt;When user accesses &lt;/span&gt;
        ///        @Html.DropDownListFor(m =&gt; m.SelectedBotTypeActivity, Model.BotTypeActivities)
        ///        @if (Model.ShowUnusualDataSection)
        ///        {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageWithHardCodedLayout {
            get {
                return ResourceManager.GetString("PageWithHardCodedLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model WebUI.Areas.Bots.Models.AdvancedBotTypeViewModel
        ///@{
        ///    ViewBag.Title = &quot;Index&quot;;
        ///}
        ///@{
        ///    Layout = MVC.Shared.Views.ViewNames._Filters;
        ///}
        ///@using (Html.BeginForm(MVC.Bots.AdvancedBotType.Save()))
        ///{
        ///    @Html.ValidationSummary(false)
        ///    &lt;fieldset&gt;
        ///        &lt;legend&gt;AdvancedBotTypeViewModel&lt;/legend&gt;&lt;span&gt;When user accesses &lt;/span&gt;
        ///        @Html.DropDownListFor(m =&gt; m.SelectedBotTypeActivity, Model.BotTypeActivities)
        ///        @if (Model.ShowUnusualDataSection)
        ///        {
        ///            &lt;div id=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageWithMVCLayout {
            get {
                return ResourceManager.GetString("PageWithMVCLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model WebUI.Areas.Bots.Models.UsersMachinesSetting
        ///@{
        ///    Layout = &quot;~/Areas/Bots/Views/Shared/_Main.cshtml&quot;;
        ///}
        ///&lt;script type=&quot;text/javascript&quot; language=&quot;javascript&quot;&gt;
        ///    $(document).ready(function () {
        ///        ToggleUsersDivs();
        ///        ToggleMachinesDivs();
        ///    });
        ///
        ///    function ToggleUsersDivs() {
        ///        if ($(&apos;#AllUsers&apos;).is(&apos;:checked&apos;)) {
        ///            $(&apos;#userName&apos;).attr(&apos;disabled&apos;, true);
        ///            $(&apos;#userName&apos;).val(&quot;&quot;);
        ///        } else {
        ///            $(&apos;#userName&apos;).removeAttr(&apos;disabled [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageWithPartialViews {
            get {
                return ResourceManager.GetString("PageWithPartialViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model WebUI.Models.FilesModel
        ///@{
        ///    AjaxOptions ajaxOpts = new AjaxOptions
        ///{
        ///    UpdateTargetId = &quot;DeletesGrid&quot;,
        ///    InsertionMode = InsertionMode.Replace,
        ///    LoadingElementId = &quot;divLoading&quot;
        ///};
        ///}
        ///@section Filters{
        ///    @using (Ajax.BeginForm(MVC.Reports.Reports.DeletesIndex(), ajaxOpts))
        ///    {
        ///        Html.RenderPartial(MVC.Reports.Shared.Views._Filters);
        ///    }
        ///}
        ///@section Title{@WebUI.Resources.DeletesTitle}
        ///@section PageName{@WebUI.Resources.DeletesTitle}
        ///
        ///            &lt;div id=&quot;divLoadin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageWithPartialViewT4MVC {
            get {
                return ResourceManager.GetString("PageWithPartialViewT4MVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model WebUI.Models.FilesModel
        ///@{
        ///    AjaxOptions ajaxOpts = new AjaxOptions
        ///{
        ///    UpdateTargetId = &quot;DeletesGrid&quot;,
        ///    InsertionMode = InsertionMode.Replace,
        ///    LoadingElementId = &quot;divLoading&quot;
        ///};
        ///}
        ///@section Filters{
        ///    @using (Ajax.BeginForm(MVC.Reports.Reports.DeletesIndex(), ajaxOpts))
        ///    {
        ///        Html.RenderPartial(MVC.Reports.Shared.Views._Filters, Model.FilesFilter);
        ///    }
        ///}
        ///@section Title{@WebUI.Resources.DeletesTitle}
        ///@section PageName{@WebUI.Resources.DeletesTitle}
        ///
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageWithSections {
            get {
                return ResourceManager.GetString("PageWithSections", resourceCulture);
            }
        }
    }
}
